# Generated by Django 5.1.7 on 2025-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
