# Generated by Django 5.1.7 on 2025-03-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_company_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Website (domain only, e.g. Netflix.com)'),
        ),
    ]
