# Generated by Django 5.1.7 on 2025-03-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
