services:
  - type: web
    name: job-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn jobtracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobtracker.settings
      - key: PYTHON_VERSION
        value: 3.10